
version: "2"
services:
  serviceoffer:
    container_name: serviceoffer
    restart: always
    build: .
    command: npm run dev
    volumes:
      - .:/usr/src/app/serviceoffer
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"
    links:
      - mongo
      
  exogtfsloader:
    container_name: exogtfsloader
    image: docker.pkg.github.com/transitco/gtfsloader/gtfsloader:latest
    restart: always
    volumes:
      - ./src/gtfs/exo_config.json:/usr/src/app/gtfsloader/gtfs/config.json
    ports:
      - "3000:3000"
    links:
      - mongo

  rtlgtfsloader:
    container_name: rtlgtfsloader
    image: docker.pkg.github.com/transitco/gtfsloader/gtfsloader:latest
    restart: always
    volumes:
      - ./src/gtfs/rtl_config.json:/usr/src/app/gtfsloader/gtfs/config.json
    ports:
      - "3001:3000"
    links:
      - mongo

  stlgtfsloader:
    container_name: stlgtfsloader
    image: docker.pkg.github.com/transitco/gtfsloader/gtfsloader:latest
    restart: always
    volumes:
      - ./src/gtfs/stl_config.json:/usr/src/app/gtfsloader/gtfs/config.json
    ports:
      - "3002:3000"
    links:
      - mongo

  #stmgtfsloader:
  #  container_name: stmgtfsloader
  #  image: docker.pkg.github.com/transitco/gtfsloader/gtfsloader:latest
  #  restart: always
  #  volumes:
  #    - ./src/gtfs/stm_config.json:/usr/src/app/gtfsloader/gtfs/config.json
  #  ports:
  #    - "3003:3000"
  #  environment:
  #  - AGENCY=stm
  #  links:
  #    - mongo
  
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"

  admin-mongo:
    container_name: adminMongo
    image: 0x59/admin-mongo:latest
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - CONN_NAME=mongo
      - DB_HOST=mongo
      - DB_PORT=27017
    links:
      - mongo

volumes: 
  data:
