version: "3"

services:
  serviceoffer:
    container_name: serviceoffer
    restart: always
    build: .
    ports:
      - "4001:4000"
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  admin-mongo:
    image: 0x59/admin-mongo:latest
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - CONN_NAME=mongo
      - DB_HOST=mongo
    links:
      - mongo

  mongoke:
    ports:
        - "4000:80"
    image: mongoke/mongoke
    environment:
        - DB_URL=mongodb://mongo/gtfs'
        - PORT=80
    volumes:
        - ./mongoke.yml:/conf.yml
    links:
      - mongo