version: "2"

services:
  serviceoffer:
    container_name: serviceoffer
    restart: always
    build: .
    ports:
      - "4000:4000"
    links:
      - mongo

  exogtfsloader:
    container_name: exogtfsloader
    image: gtfsloader
    restart: always
    volumes:
      - ./gtfs/exo_config.json:/usr/src/app/gtfsloader/gtfs/config.json
    links:
      - mongo

  rtlgtfsloader:
    container_name: rtlgtfsloader
    image: gtfsloader
    restart: always
    volumes:
      - ./gtfs/rtl_config.json:/usr/src/app/gtfsloader/gtfs/config.json
    links:
      - mongo

  stmgtfsloader:
    container_name: stmgtfsloader
    image: gtfsloader
    restart: always
    volumes:
      - ./gtfs/stm_config.json:/usr/src/app/gtfsloader/gtfs/config.json
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  admin-mongo:
    image: 0x59/admin-mongo:latest
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - CONN_NAME=mongo
      - DB_HOST=mongo
    links:
      - mongo