version: "2"

services:
  serviceoffer:
    container_name: serviceoffer
    restart: always
    build: .
    command: npm run dev
    volumes:
      - .:/usr/src/app/serviceoffer
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"
    links:
      - mongo

  exogtfsloader:
    container_name: exogtfsloader
    build: https://github.com/transtico/GTFSloader.git
    restart: always
    volumes:
      - ./test/exo_citso_gtsf_config_test.json:/usr/src/app/gtfsloader/gtfs/config.json
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data_test:/data/db
    ports:
      - "27017:27017"

  admin-mongo:
    container_name: adminMongo
    image: 0x59/admin-mongo:latest
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - CONN_NAME=mongo
      - DB_HOST=mongo
      - DB_PORT=27017
    links:
      - mongo
volumes: 
  data:
